[package]
name = "rsboot"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"

[dependencies]
log = "0.4.33"
uefi = { version = "0.39.0", features = ["alloc", "global_allocator", "logger", "panic_handler"] }
hadris-iso = { git = "https://github.com/hxyulin/hadris", rev = "fae5e477", default-features = false, features = ["read", "alloc", "sync"] }
hadris-io = { git = "https://github.com/hxyulin/hadris", rev = "fae5e477", default-features = false, features = ["sync", "alloc"] }
sha2 = { version = "0.11", default-features = false }
