port=0
interface=eth0
bind-interfaces
dhcp-range=192.168.44.50,192.168.44.254,12h
dhcp-option=option:router,192.168.44.1
enable-tftp
tftp-root=/srv/tftp
dhcp-match=set:efi-x64,option:client-arch,7 
dhcp-match=set:efi-arm64,option:client-arch,11
dhcp-boot=tag:efi-x64,bootx64.efi
dhcp-boot=tag:efi-arm64,bootaa64.efi
